//! vortex_core — PyC Unified HPC Runtime
//!
//! This crate is the execution engine layer of the unified PyC toolchain.
//! It provides:
//!   - Asynchronous CPU→GPU dispatch pipeline (conveyor belt)
//!   - NUMA-aware pinned memory allocator
//!   - Hardware topology profiler
//!   - Telemetry broadcaster
//!   - Safe Rust FFI wrappers around the PyC C compiler layer
//!
//! The crate links against `libpyc_compiler.so` at runtime via the C-ABI
//! bridge defined in `ffi/mod.rs`. Bindings are generated by `build.rs`
//! using bindgen from the PyC public headers in `include/pyc/`.

pub mod allocator;
pub mod cpu_dispatch;
pub mod errors;
pub mod ffi;
pub mod hw_profile;
pub mod integrations;
pub mod kernel_registry;
pub mod pipeline;
pub mod telemetry;

// Re-export the most commonly used types at the crate root
pub use allocator::{Allocator, AllocatorConfig};
pub use cpu_dispatch::{CpuDispatcher, DispatchHandle};
pub use errors::VortexError;
pub use ffi::{PycError, build_alloc_plan, compile, cuda_dispatch, run, select_kernel};
pub use hw_profile::{HardwareProfile, detect_hardware};
pub use pipeline::{Pipeline, PipelineConfig, PipelineStats};
pub use telemetry::{TelemetryEvent, TelemetrySink};

/// Convenience: initialize the runtime with hardware-aware defaults.
/// Detects hardware, configures the allocator and dispatcher, and
/// returns a ready-to-use `Pipeline`.
pub fn init() -> Result<Pipeline, VortexError> {
    let _ = env_logger::try_init();
    let hw = detect_hardware();
    log::info!(
        "PyC runtime init: {} CPU cores, {} NUMA nodes, {} GPU(s)",
        hw.cpu_cores,
        hw.numa_nodes,
        hw.gpu_count
    );
    Pipeline::new(PipelineConfig::from_hardware(&hw))
}
