//! vortex_core — PyC Unified HPC Runtime
//!
//! This crate is the execution engine layer of the unified PyC toolchain.
//! It provides:
//!   - Asynchronous CPU→GPU dispatch pipeline (conveyor belt)
//!   - NUMA-aware pinned memory allocator
//!   - Hardware topology profiler
//!   - Telemetry broadcaster
//!   - Safe Rust FFI wrappers around the PyC C compiler layer
//!
//! The crate links against `libpyc_compiler.so` at runtime via the C-ABI
//! bridge defined in `ffi/mod.rs`. Bindings are generated by `build.rs`
//! using bindgen from the PyC public headers in `include/pyc/`.

#[cfg(not(feature = "python_ext"))]
pub mod allocator;
#[cfg(not(feature = "python_ext"))]
pub mod cpu_dispatch;
#[cfg(not(feature = "python_ext"))]
pub mod errors;
#[cfg(not(feature = "python_ext"))]
pub mod ffi;
pub mod hw_profile;
#[cfg(not(feature = "python_ext"))]
pub mod integrations;
#[cfg(not(feature = "python_ext"))]
pub mod pipeline;
#[cfg(not(feature = "python_ext"))]
pub mod telemetry;

// Re-export the most commonly used types at the crate root
#[cfg(not(feature = "python_ext"))]
pub use allocator::{Allocator, AllocatorConfig};
#[cfg(not(feature = "python_ext"))]
pub use cpu_dispatch::{CpuDispatcher, DispatchHandle};
#[cfg(not(feature = "python_ext"))]
pub use errors::VortexError;
#[cfg(not(feature = "python_ext"))]
pub use ffi::{
    build_alloc_plan, compile, compile_model, cuda_dispatch, run, select_kernel, PycError,
};
pub use hw_profile::{detect_hardware, HardwareProfile};
#[cfg(not(feature = "python_ext"))]
pub use pipeline::{Pipeline, PipelineConfig, PipelineStats};
#[cfg(not(feature = "python_ext"))]
pub use telemetry::{TelemetryEvent, TelemetrySink};

#[cfg(feature = "python_ext")]
mod py_ext {
    use super::hw_profile;
    use pyo3::prelude::*;

    #[pyclass(name = "HardwareProfile")]
    pub struct PyHardwareProfile {
        #[pyo3(get)]
        pub cpu_cores: usize,
        #[pyo3(get)]
        pub numa_nodes: usize,
        #[pyo3(get)]
        pub gpu_count: usize,
        #[pyo3(get)]
        pub gpu_numa_node: Option<usize>,
        #[pyo3(get)]
        pub total_ram_bytes: u64,
        #[pyo3(get)]
        pub cpu_arch: String,
    }

    impl From<hw_profile::HardwareProfile> for PyHardwareProfile {
        fn from(profile: hw_profile::HardwareProfile) -> Self {
            Self {
                cpu_cores: profile.cpu_cores,
                numa_nodes: profile.numa_nodes,
                gpu_count: profile.gpu_count,
                gpu_numa_node: profile.gpu_numa_node,
                total_ram_bytes: profile.total_ram_bytes,
                cpu_arch: profile.cpu_arch,
            }
        }
    }

    #[pyfunction]
    pub fn detect_hardware() -> PyHardwareProfile {
        hw_profile::detect_hardware().into()
    }

    #[pymodule]
    pub fn _vortex_core(_py: Python<'_>, module: &PyModule) -> PyResult<()> {
        module.add_class::<PyHardwareProfile>()?;
        module.add_function(wrap_pyfunction!(detect_hardware, module)?)?;
        Ok(())
    }
}

/// Convenience: initialize the runtime with hardware-aware defaults.
/// Detects hardware, configures the allocator and dispatcher, and
/// returns a ready-to-use `Pipeline`.
#[cfg(not(feature = "python_ext"))]
pub fn init() -> Result<Pipeline, VortexError> {
    let _ = env_logger::try_init();
    let hw = detect_hardware();
    log::info!(
        "PyC runtime init: {} CPU cores, {} NUMA nodes, {} GPU(s)",
        hw.cpu_cores,
        hw.numa_nodes,
        hw.gpu_count
    );
    Pipeline::new(PipelineConfig::from_hardware(&hw))
}
