name: Feature request
description: Propose an improvement with clear value and acceptance criteria
labels: [enhancement]
body:
  - type: input
    id: problem
    attributes:
      label: Problem statement
      placeholder: What limitation are you hitting?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      placeholder: Describe design, interfaces, and constraints
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      placeholder: Testable outcomes for completion
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
