//! ffi/mod.rs — Safe Rust wrappers around the raw PyC compiler C-ABI.
//!
//! The raw bindings are generated by build.rs via bindgen and placed in
//! $OUT_DIR/pyc_bindings.rs. This module provides ergonomic, safe Rust
//! types on top of those raw bindings.

#![allow(non_upper_case_globals, non_camel_case_types, non_snake_case, dead_code)]

// Include the bindgen-generated raw bindings
include!(concat!(env!("OUT_DIR"), "/pyc_bindings.rs"));

use std::ffi::CStr;
use thiserror::Error;

// ----------------------------------------------------------------
// Error types
// ----------------------------------------------------------------

#[derive(Debug, Error)]
pub enum PycError {
    #[error("PyC compile failed: {0}")]
    CompileError(String),
    #[error("PyC run failed with status {0}")]
    RunError(i32),
    #[error("PyC kernel selection failed for op: {0}")]
    KernelSelectError(String),
    #[error("PyC memory plan build failed")]
    AllocPlanError,
    #[error("PyC CUDA dispatch error")]
    CudaDispatchError,
    #[error("Null pointer returned from PyC")]
    NullPointer,
}

// ----------------------------------------------------------------
// Safe wrapper: compile an IR module
// ----------------------------------------------------------------

/// Compiles a `pyc_ir_module` with the given options.
/// Returns Ok(()) on success, or a `PycError` describing the failure.
pub fn compile(
    module: &mut pyc_ir_module,
    options: &pyc_compile_options,
) -> Result<(), PycError> {
    let status = unsafe { pyc_compile(module as *mut _, options as *const _) };
    if status == 0 {
        Ok(())
    } else {
        Err(PycError::CompileError(format!("status={}", status)))
    }
}

// ----------------------------------------------------------------
// Safe wrapper: run a compiled IR module
// ----------------------------------------------------------------

/// Executes a compiled `pyc_ir_module` with the given inputs/outputs.
pub fn run(
    module: &pyc_ir_module,
    inputs: &[pyc_tensor],
    outputs: &mut [pyc_tensor],
) -> Result<pyc_run_stats, PycError> {
    let mut stats = pyc_run_stats::default();
    let status = unsafe {
        pyc_run(
            module as *const _,
            inputs.as_ptr(),
            inputs.len(),
            outputs.as_mut_ptr(),
            outputs.len(),
            &mut stats as *mut _,
        )
    };
    if status == 0 {
        Ok(stats)
    } else {
        Err(PycError::RunError(status))
    }
}

// ----------------------------------------------------------------
// Safe wrapper: policy-driven kernel selection
// ----------------------------------------------------------------

/// Selects the best kernel for `op_key` on `backend` given the current
/// optimizer policy mode and memory pressure score.
pub fn select_kernel(
    op_key: &str,
    backend: pyc_backend,
    mode: pyc_objective_mode,
    pressure: f64,
) -> Result<pyc_kernel_desc, PycError> {
    let key = std::ffi::CString::new(op_key)
        .map_err(|_| PycError::KernelSelectError(op_key.to_string()))?;
    let mut out = pyc_kernel_desc::default();
    let mut trace = pyc_kernel_selection_trace::default();
    let found = unsafe {
        pyc_kernel_select_with_policy(
            key.as_ptr(),
            backend,
            mode,
            pressure,
            &mut out as *mut _,
            &mut trace as *mut _,
        )
    };
    if found == 1 {
        Ok(out)
    } else {
        Err(PycError::KernelSelectError(op_key.to_string()))
    }
}

// ----------------------------------------------------------------
// Safe wrapper: memory allocation planning
// ----------------------------------------------------------------

/// Builds an optimized memory allocation plan for the given requests,
/// respecting the policy mode and optional memory budget.
pub fn build_alloc_plan(
    plan: &mut pyc_alloc_plan,
    mode: pyc_objective_mode,
    budget_bytes: usize,
) -> Result<pyc_alloc_stats, PycError> {
    let status = unsafe {
        pyc_alloc_plan_build_with_mode(plan as *mut _, mode, budget_bytes)
    };
    if status == 0 {
        let mut stats = pyc_alloc_stats::default();
        unsafe { pyc_alloc_plan_stats(plan as *const _, &mut stats as *mut _) };
        Ok(stats)
    } else {
        Err(PycError::AllocPlanError)
    }
}

// ----------------------------------------------------------------
// Safe wrapper: CUDA dispatch with CPU fallback
// ----------------------------------------------------------------

/// Dispatches execution of a compiled module to CUDA if available,
/// falling back to the provided CPU executor on failure.
pub fn cuda_dispatch(
    module: &pyc_ir_module,
    inputs: &[pyc_tensor],
    outputs: &mut [pyc_tensor],
    cpu_executor: pyc_cpu_executor_fn,
    ctx: *mut std::ffi::c_void,
) -> Result<bool, PycError> {
    let mut trace = pyc_cuda_dispatch_trace::default();
    let status = unsafe {
        pyc_cuda_dispatch(
            module as *const _,
            inputs.as_ptr(),
            inputs.len(),
            outputs.as_mut_ptr(),
            outputs.len(),
            cpu_executor,
            ctx,
            &mut trace as *mut _,
        )
    };
    match status {
        pyc_cuda_dispatch_status::PYC_CUDA_DISPATCH_OK => Ok(false),       // ran on GPU
        pyc_cuda_dispatch_status::PYC_CUDA_DISPATCH_FALLBACK => Ok(true),  // fell back to CPU
        _ => Err(PycError::CudaDispatchError),
    }
}
